#!/usr/bin/env python
# -*- coding: utf-8 -*-
# generated by wxGlade 0.6.3 on Thu Feb 21 09:32:18 2013

import wx

# begin wxGlade: extracode
# end wxGlade



class MyFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MyFrame.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.text_ctrl_1 = wx.TextCtrl(self, -1, "")
        self.text_ctrl_2 = wx.TextCtrl(self, -1, "")
        self.combo_box_1 = wx.ComboBox(self, -1, choices=[], style=wx.CB_DROPDOWN)
        self.button_1 = wx.Button(self, -1, "Copiar")
        self.button_2 = wx.Button(self, -1, "Borrar")
        self.button_3 = wx.Button(self, -1, "Salir")
        
        # Menu Bar
        self.Ejemplo_menubar = wx.MenuBar()
        wxglade_tmp_menu = wx.Menu()
        wxglade_tmp_menu.Append(1, "Exit", "", wx.ITEM_NORMAL)
        self.Ejemplo_menubar.Append(wxglade_tmp_menu, "File")
        self.SetMenuBar(self.Ejemplo_menubar)
        # Menu Bar end

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_BUTTON, self.Copiar, self.button_1)
        self.Bind(wx.EVT_BUTTON, self.Borrar, self.button_2)
        self.Bind(wx.EVT_BUTTON, self.Salir, self.button_3)
        self.Bind(wx.EVT_MENU, self.Salir, id=1)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: MyFrame.__set_properties
        self.SetTitle("Ejemplo")
        self.SetSize((400, 100))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MyFrame.__do_layout
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        sizer_2 = wx.BoxSizer(wx.VERTICAL)
        sizer_4 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_3 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_3.Add(self.text_ctrl_1, 0, 0, 0)
        sizer_3.Add(self.text_ctrl_2, 0, 0, 0)
        sizer_3.Add(self.combo_box_1, 0, 0, 0)
        sizer_2.Add(sizer_3, 1, wx.EXPAND, 0)
        sizer_4.Add(self.button_1, 0, 0, 0)
        sizer_4.Add(self.button_2, 0, 0, 0)
        sizer_4.Add(self.button_3, 0, 0, 0)
        sizer_2.Add(sizer_4, 1, wx.EXPAND, 0)
        sizer_1.Add(sizer_2, 1, wx.EXPAND, 0)
        self.SetSizer(sizer_1)
        self.Layout()
        # end wxGlade

    def Salir(self, event): # wxGlade: MyFrame.<event_handler>
	self.Destroy()

    def Copiar(self, event): # wxGlade: MyFrame.<event_handler>
        texto1 = self.text_ctrl_1.GetValue()
	self.text_ctrl_2.SetValue(texto1)

    def Borrar(self, event): # wxGlade: MyFrame.<event_handler>
        self.text_ctrl_1.SetValue('')
	self.text_ctrl_2.SetValue('')

# end of class MyFrame


if __name__ == "__main__":
    app = wx.PySimpleApp(0)
    wx.InitAllImageHandlers()
    Ejemplo = MyFrame(None, -1, "")
    app.SetTopWindow(Ejemplo)
    Ejemplo.Show()
    app.MainLoop()
