#!/usr/bin/env python
# -*- coding: utf-8 -*-
# generated by wxGlade 0.6.4 on Wed Feb 20 19:42:11 2013

import wx
from controlador import *
from sqlalchemy import *



# begin wxGlade: extracode
# end wxGlade


class MyFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MyFrame.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.notebook_1 = wx.Notebook(self, -1, style=0)
        self.notebook_1_pane_1 = wx.Panel(self.notebook_1, -1)
        self.label_2 = wx.StaticText(self.notebook_1_pane_1, -1, "Autor", style=wx.ALIGN_CENTRE)
        self.label_3 = wx.StaticText(self.notebook_1_pane_1, -1, u"Título", style=wx.ALIGN_CENTRE)
        self.button_3 = wx.Button(self.notebook_1_pane_1, -1, "Buscar")
        self.combo_box_1 = wx.ComboBox(self.notebook_1_pane_1, -1, choices=[], style=wx.CB_DROPDOWN)
        self.text_ctrl_2 = wx.TextCtrl(self.notebook_1_pane_1, -1, "")
        self.listCtrl = wx.ListCtrl(self.notebook_1_pane_1, -1, style=wx.LC_REPORT | wx.SUNKEN_BORDER)
        self.notebook_1_pane_2 = wx.Panel(self.notebook_1, -1)
        
        # Menu Bar
        self.frame_1_menubar = wx.MenuBar()
        wxglade_tmp_menu = wx.Menu()
        wxglade_tmp_menu.Append(1, "Conect", "", wx.ITEM_NORMAL)
        wxglade_tmp_menu.Append(2, "Exit", "", wx.ITEM_NORMAL)
        self.frame_1_menubar.Append(wxglade_tmp_menu, "File")
        self.SetMenuBar(self.frame_1_menubar)
        # Menu Bar end

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_BUTTON, self.Buscar_libro, self.button_3)
        self.Bind(wx.EVT_MENU, self.Conectar_db, id=1)
        self.Bind(wx.EVT_MENU, self.Salir, id=2)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: MyFrame.__set_properties
        self.SetTitle("frame_1")
        self.SetSize((634, 443))
        self.label_2.SetMinSize((44, 25))
        self.label_2.SetFont(wx.Font(10, wx.DEFAULT, wx.NORMAL, wx.BOLD, 0, ""))
        self.label_3.SetMinSize((44, 25))
        self.label_3.SetFont(wx.Font(10, wx.DEFAULT, wx.NORMAL, wx.BOLD, 0, ""))
        self.button_3.SetFont(wx.Font(10, wx.DEFAULT, wx.NORMAL, wx.BOLD, 0, ""))
        self.combo_box_1.SetMinSize((185, 25))
        self.text_ctrl_2.SetMinSize((300, 25))
        # end wxGlade
        self.listCtrl.InsertColumn(0, "Título")
        self.listCtrl.SetColumnWidth(0,250)
        self.listCtrl.InsertColumn(1, "Editorial")
        self.listCtrl.SetColumnWidth(1,120)
        self.listCtrl.InsertColumn(2, "Fecha")
        self.listCtrl.InsertColumn(2, "Precio")
        self.combo_box_1.Append('Michael')
        
    def __do_layout(self):
        # begin wxGlade: MyFrame.__do_layout
        sizer_5 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_7 = wx.BoxSizer(wx.VERTICAL)
        sizer_8 = wx.BoxSizer(wx.VERTICAL)
        sizer_14 = wx.BoxSizer(wx.VERTICAL)
        sizer_15 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_17 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_18 = wx.BoxSizer(wx.VERTICAL)
        sizer_16 = wx.BoxSizer(wx.VERTICAL)
        sizer_16.Add((20, 5), 0, 0, 0)
        sizer_16.Add(self.label_2, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)
        sizer_16.Add(self.label_3, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)
        sizer_16.Add((20, 3), 0, 0, 0)
        sizer_16.Add(self.button_3, 0, 0, 0)
        sizer_15.Add(sizer_16, 1, 0, 0)
        sizer_18.Add(self.combo_box_1, 0, 0, 0)
        sizer_18.Add(self.text_ctrl_2, 0, 0, 0)
        sizer_17.Add(sizer_18, 1, 0, 0)
        sizer_15.Add(sizer_17, 0, 0, 0)
        sizer_14.Add(sizer_15, 1, 0, 0)
        sizer_8.Add(sizer_14, 1, wx.EXPAND, 0)
        sizer_7.Add(sizer_8, 1, wx.EXPAND, 0)
        sizer_7.Add(self.listCtrl, 3, wx.EXPAND, 0)
        self.notebook_1_pane_1.SetSizer(sizer_7)
        self.notebook_1.AddPage(self.notebook_1_pane_1, "Buscar Libros")
        self.notebook_1.AddPage(self.notebook_1_pane_2, "Insertar Libros")
        sizer_5.Add(self.notebook_1, 1, wx.EXPAND, 0)
        self.SetSizer(sizer_5)
        self.Layout()
        # end wxGlade

    def Salir(self, event):  # wxGlade: MyFrame.<event_handler>
        #print "Event handler `Salir' not implemented"
        self.Destroy()
        #event.Skip()

    def Conectar_db(self, event):  # wxGlade: MyFrame.<event_handler>
        BBDD.conectar_bd()


    def Buscar_libro(self, event):  # wxGlade: MyFrame.<event_handler>
        self.listCtrl.DeleteAllItems()
        autor=self.combo_box_1.GetValue()
        titulo=self.text_ctrl_2.GetValue()
        libros=BBDD.busca_libro_sql(titulo,autor)
        
        # Muestra en el listCtrl los resultados de la Query
        for (a,l) in libros:
            #print l.titulo,'--',a.nombre
            tmp=[l.titulo,l.editorial,l.precio,l.fecha]
            self.listCtrl.Append([str(x).decode('latin1') for x in tmp])

            


        

# end of class MyFrame
if __name__ == "__main__":
    BBDD=Database()
    app = wx.PySimpleApp(0)
    wx.InitAllImageHandlers()
    frame_1 = MyFrame(None, -1, "")
    app.SetTopWindow(frame_1)
    frame_1.Show()
    app.MainLoop()
